# onomastica-geo.py
# a wrapper dict for the "comarques"

GEO_DICT = {'Alt Camp': 'com:01',
    'Alt Empordà': 'com:02',
    'Alt Penedès': 'com:03',
    'Alt Urgell': 'com:04',
    'Alta Ribagorça': 'com:05',
    'Anoia': 'com:06',
    'Bages': 'com:07',
    'Baix Camp': 'com:08',
    'Baix Ebre': 'com:09',
    'Baix Empordà': 'com:10',
    'Baix Llobregat': 'com:11',
    'Baix Penedès': 'com:12',
    'Barcelonès': 'com:13',
    'Berguedà': 'com:14',
    'Cerdanya': 'com:15',
    'Conca De Barberà': 'com:16', # mal escrit per qüestion pràctiques
    'Garraf': 'com:17',
    'Garrigues': 'com:18',
    'Garrotxa': 'com:19',
    'Gironès': 'com:20',
    'Maresme': 'com:21',
    'Montsià': 'com:22',
    'Noguera': 'com:23',
    'Osona': 'com:24',
    'Pallars Jussà': 'com:25',
    'Pallars Sobirà': 'com:26',
    "Pla de l'Estany": 'com:27',
    "Pla d'Urgell": 'com:28',
    'Priorat': 'com:29',
    "Ribera d'Ebre": 'com:30',
    'Ripollès': 'com:31',
    'Segarra': 'com:32',
    'Segrià': 'com:33',
    'Selva': 'com:34',
    'Solsonès': 'com:35',
    'Tarragonès': 'com:36',
    'Terra Alta': 'com:37',
    'Urgell': 'com:38',
    "Val d'Aran": 'com:39',
    'Vallès Occidental': 'com:40',
    'Vallès Oriental': 'com:41',
    }
